# Generated by Django 5.2.5 on 2026-04-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("plans", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "session_type",
                    models.CharField(
                        default="daily", max_length=32, verbose_name="会话类型"
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(default=0, verbose_name="总题数"),
                ),
                (
                    "finished_count",
                    models.PositiveIntegerField(default=0, verbose_name="完成题数"),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(default=0, verbose_name="答对题数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "进行中"), ("completed", "已完成")],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_sessions",
                        to="plans.userplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_sessions",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "复习会话",
                "verbose_name_plural": "复习会话",
                "db_table": "review_sessions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question_type",
                    models.CharField(
                        default="meaning_to_word", max_length=32, verbose_name="题型"
                    ),
                ),
                (
                    "user_answer",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="用户答案"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="正确答案"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确"),
                ),
                ("reviewed_at", models.DateTimeField(verbose_name="复习时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_records",
                        to="users.wxuser",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_records",
                        to="books.word",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="review.reviewsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "复习记录",
                "verbose_name_plural": "复习记录",
                "db_table": "review_records",
                "ordering": ["-reviewed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WrongWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "wrong_count",
                    models.PositiveIntegerField(default=1, verbose_name="错误次数"),
                ),
                (
                    "source",
                    models.CharField(
                        default="review", max_length=16, verbose_name="来源"
                    ),
                ),
                ("last_wrong_at", models.DateTimeField(verbose_name="最近错误时间")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否仍在错词本"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_words",
                        to="users.wxuser",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_word_users",
                        to="books.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "错词本",
                "verbose_name_plural": "错词本",
                "db_table": "wrong_words",
                "ordering": ["-last_wrong_at", "-id"],
                "unique_together": {("user", "word")},
            },
        ),
    ]
