# Generated by Django 5.2.5 on 2026-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrecord",
            name="answer_feedback",
            field=models.JSONField(blank=True, default=dict, verbose_name="答题反馈"),
        ),
    ]
