from django.urls import path

from .views import (
    AICapabilityView,
    AIConversationAskView,
    AIConversationDetailView,
    AIConversationListCreateView,
    AIFeedbackView,
    AIGrammarTutorView,
    AIGrammarGuideView,
    AIRAGIndexSyncView,
    AIRAGIndexStatusView,
    AIRetrievalOrchestratorView,
    AIMCPManifestView,
    AIMCPPromptsView,
    AIMCPResourceReadView,
    AIMCPResourcesView,
    AIMCPToolCallView,
    AIMultiAgentBriefView,
    AIObservabilityView,
    AIProfileMemoryView,
    AIPlanReplanView,
    AIQualityView,
    AIEvaluationView,
    AIEvaluationRunDetailView,
    AIEvaluationRunReplayView,
    AIRAGRecallEvaluateView,
    AIRAGSearchView,
    AIScenarioTemplateListView,
    AIScenarioDialogueView,
    AIStudyReportView,
    AIStudyCoachView,
    AITranslationEvaluateView,
    AIVectorRAGSearchView,
    AIWordTutorView,
    AIWritingCorrectView,
    AIWritingPromptView,
    AIWrongWordsReviewView,
)

urlpatterns = [
    path("ai/capabilities", AICapabilityView.as_view(), name="ai-capabilities"),
    path("ai/grammar/tutor", AIGrammarTutorView.as_view(), name="ai-grammar-tutor"),
    path("ai/words/explain", AIWordTutorView.as_view(), name="ai-word-tutor"),
    path("ai/study-coach", AIStudyCoachView.as_view(), name="ai-study-coach"),
    path("ai/plans/replan", AIPlanReplanView.as_view(), name="ai-plan-replan"),
    path("ai/agents/retrieval-orchestrator", AIRetrievalOrchestratorView.as_view(), name="ai-retrieval-orchestrator"),
    path("ai/wrong-words/review", AIWrongWordsReviewView.as_view(), name="ai-wrong-words-review"),
    path("ai/writing/correct", AIWritingCorrectView.as_view(), name="ai-writing-correct"),
    path("ai/writing/prompt", AIWritingPromptView.as_view(), name="ai-writing-prompt"),
    path("ai/translation/evaluate", AITranslationEvaluateView.as_view(), name="ai-translation-evaluate"),
    path("ai/grammar/guide", AIGrammarGuideView.as_view(), name="ai-grammar-guide"),
    path("ai/rag/search", AIRAGSearchView.as_view(), name="ai-rag-search"),
    path("ai/rag/index-status", AIRAGIndexStatusView.as_view(), name="ai-rag-index-status"),
    path("ai/rag/index-sync", AIRAGIndexSyncView.as_view(), name="ai-rag-index-sync"),
    path("ai/rag/vector-search", AIVectorRAGSearchView.as_view(), name="ai-rag-vector-search"),
    path("ai/rag/recall-evaluate", AIRAGRecallEvaluateView.as_view(), name="ai-rag-recall-evaluate"),
    path("ai/scenario/templates", AIScenarioTemplateListView.as_view(), name="ai-scenario-templates"),
    path("ai/scenario/dialogue", AIScenarioDialogueView.as_view(), name="ai-scenario-dialogue"),
    path("ai/agents/brief", AIMultiAgentBriefView.as_view(), name="ai-agents-brief"),
    path("ai/quality", AIQualityView.as_view(), name="ai-quality"),
    path("ai/observability", AIObservabilityView.as_view(), name="ai-observability"),
    path("ai/profile-memory", AIProfileMemoryView.as_view(), name="ai-profile-memory"),
    path("ai/evaluations", AIEvaluationView.as_view(), name="ai-evaluations"),
    path("ai/evaluations/runs/<int:run_id>", AIEvaluationRunDetailView.as_view(), name="ai-evaluation-run-detail"),
    path("ai/evaluations/runs/<int:run_id>/replay", AIEvaluationRunReplayView.as_view(), name="ai-evaluation-run-replay"),
    path("ai/reports", AIStudyReportView.as_view(), name="ai-reports"),
    path("ai/conversations", AIConversationListCreateView.as_view(), name="ai-conversations"),
    path("ai/conversations/ask", AIConversationAskView.as_view(), name="ai-conversations-ask"),
    path("ai/conversations/<int:conversation_id>", AIConversationDetailView.as_view(), name="ai-conversation-detail"),
    path("ai/feedback", AIFeedbackView.as_view(), name="ai-feedback"),
    path("ai/mcp/manifest", AIMCPManifestView.as_view(), name="ai-mcp-manifest"),
    path("ai/mcp/resources", AIMCPResourcesView.as_view(), name="ai-mcp-resources"),
    path("ai/mcp/prompts", AIMCPPromptsView.as_view(), name="ai-mcp-prompts"),
    path("ai/mcp/resources/read", AIMCPResourceReadView.as_view(), name="ai-mcp-resource-read"),
    path("ai/mcp/tools/call", AIMCPToolCallView.as_view(), name="ai-mcp-tool-call"),
]
