# Generated by Django 5.2.5 on 2026-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="标题")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="内容"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "公告横幅",
                "verbose_name_plural": "公告横幅",
                "db_table": "banner_notices",
                "ordering": ["sort_order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="配置键"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="配置名称")),
                (
                    "value",
                    models.TextField(blank=True, default="", verbose_name="配置值"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="描述"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_configs",
                "ordering": ["id"],
            },
        ),
    ]
