# Generated by Django 5.2.5 on 2026-04-08 14:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WxUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "openid",
                    models.CharField(max_length=64, unique=True, verbose_name="OpenID"),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="UnionID"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, default="", verbose_name="头像"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="性别"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近登录时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "小程序用户",
                "verbose_name_plural": "小程序用户",
                "db_table": "users",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "daily_target",
                    models.PositiveIntegerField(default=20, verbose_name="每日目标"),
                ),
                (
                    "reminder_time",
                    models.TimeField(
                        default=datetime.time(20, 30), verbose_name="提醒时间"
                    ),
                ),
                (
                    "auto_play_audio",
                    models.BooleanField(default=True, verbose_name="自动播放发音"),
                ),
                (
                    "review_enabled",
                    models.BooleanField(default=True, verbose_name="启用复习"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户设置",
                "verbose_name_plural": "用户设置",
                "db_table": "user_settings",
            },
        ),
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "token",
                    models.CharField(max_length=128, unique=True, verbose_name="令牌"),
                ),
                ("expired_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录令牌",
                "verbose_name_plural": "登录令牌",
                "db_table": "login_tokens",
                "ordering": ["-id"],
            },
        ),
    ]
