# Generated by Django 5.2.5 on 2026-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersetting_theme_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="custom_theme",
            field=models.JSONField(blank=True, default=dict, verbose_name="自定义主题"),
        ),
    ]
