# Generated by Django 5.2.5 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_change_default_theme_to_busuu_ocean"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="cefr_level",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="CEFR等级"
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="last_reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="上次提醒发送时间"
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="placement_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="分级测试完成时间"
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="placement_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="分级测试得分"
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="reminder_subscription_status",
            field=models.CharField(
                default="unknown", max_length=16, verbose_name="提醒订阅状态"
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="reminder_template_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="提醒模板ID"),
        ),
    ]
