# Generated by Django 5.2.5 on 2026-04-29 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usersetting_cefr_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("experience", "使用体验"),
                            ("bug", "问题反馈"),
                            ("content", "内容纠错"),
                            ("ai", "AI 功能"),
                            ("other", "其他"),
                        ],
                        default="experience",
                        max_length=32,
                        verbose_name="反馈类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "contact",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="联系方式"
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="来源页面"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="小程序版本"
                    ),
                ),
                (
                    "system_info",
                    models.JSONField(blank=True, default=dict, verbose_name="设备信息"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已处理"),
                            ("ignored", "不处理"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, default="", verbose_name="管理员备注"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_user_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_items",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "意见反馈",
                "verbose_name_plural": "意见反馈",
                "db_table": "user_feedback",
                "ordering": ["-id"],
            },
        ),
    ]
