# Generated by Django 5.2.5 on 2026-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="speech_speed",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=3, verbose_name="发音语速"
            ),
        ),
    ]
