# Generated by Django 5.2.5 on 2026-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usersetting_speech_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="personalized_rag_chunk_count",
            field=models.PositiveIntegerField(default=0, verbose_name="个性化RAG知识块数"),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="personalized_rag_enabled",
            field=models.BooleanField(default=False, verbose_name="启用个性化RAG"),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="personalized_rag_last_error",
            field=models.TextField(blank=True, default="", verbose_name="个性化RAG最近错误"),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="personalized_rag_status",
            field=models.CharField(
                choices=[("idle", "未创建"), ("building", "构建中"), ("ready", "可用"), ("failed", "失败")],
                default="idle",
                max_length=16,
                verbose_name="个性化RAG状态",
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="personalized_rag_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="个性化RAG更新时间"),
        ),
    ]
