# Generated by Django 5.2.5 on 2026-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataImportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task_name",
                    models.CharField(max_length=128, verbose_name="任务名称"),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="文件名"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="成功数量"),
                ),
                (
                    "fail_count",
                    models.PositiveIntegerField(default=0, verbose_name="失败数量"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="执行时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "数据导入任务",
                "verbose_name_plural": "数据导入任务",
                "db_table": "data_import_tasks",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("module", models.CharField(max_length=64, verbose_name="模块")),
                ("action", models.CharField(max_length=64, verbose_name="动作")),
                (
                    "operator",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="操作人"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "operation_logs",
                "ordering": ["-id"],
            },
        ),
    ]
