# Generated by Django 5.2.5 on 2026-04-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "daily_target",
                    models.PositiveIntegerField(default=20, verbose_name="每日目标"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("paused", "暂停"),
                            ("completed", "完成"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "finished_word_count",
                    models.PositiveIntegerField(default=0, verbose_name="已完成单词数"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
                "db_table": "user_plans",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DailyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("task_date", models.DateField(verbose_name="任务日期")),
                (
                    "new_word_target",
                    models.PositiveIntegerField(default=20, verbose_name="新词目标"),
                ),
                (
                    "review_word_target",
                    models.PositiveIntegerField(default=10, verbose_name="复习目标"),
                ),
                (
                    "learned_count",
                    models.PositiveIntegerField(default=0, verbose_name="已学数量"),
                ),
                (
                    "reviewed_count",
                    models.PositiveIntegerField(default=0, verbose_name="已复习数量"),
                ),
                (
                    "test_count",
                    models.PositiveIntegerField(default=0, verbose_name="已测试数量"),
                ),
                (
                    "is_started",
                    models.BooleanField(default=False, verbose_name="是否开始"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_tasks",
                        to="users.wxuser",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_tasks",
                        to="plans.userplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日任务",
                "verbose_name_plural": "每日任务",
                "db_table": "daily_tasks",
                "ordering": ["-task_date", "-id"],
                "unique_together": {("user", "task_date")},
            },
        ),
    ]
