# Generated by Django 5.2.5 on 2026-05-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
        ("users", "0007_usersetting_speech_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("manual", "Manual"),
                            ("ai_agent", "AI Agent"),
                            ("rollback", "Rollback"),
                            ("switch_book", "Switch Book"),
                        ],
                        default="manual",
                        max_length=24,
                        verbose_name="Source",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Summary"
                    ),
                ),
                (
                    "patch_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Patch Payload"
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Before Snapshot"
                    ),
                ),
                (
                    "after_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="After Snapshot"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="plans.userplan",
                    ),
                ),
                (
                    "rollback_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_children",
                        to="plans.planrevision",
                        verbose_name="Rollback From",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_revisions",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Revision",
                "verbose_name_plural": "Plan Revision",
                "db_table": "plan_revisions",
                "ordering": ["-id"],
            },
        ),
    ]
