# Generated by Django 5.2.5 on 2026-04-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0007_usersetting_speech_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("grammar", "语法问答"),
                            ("word", "AI讲词"),
                            ("study_coach", "学习教练"),
                            ("wrong_words", "错词复盘"),
                            ("writing", "写作批改"),
                            ("translation", "翻译训练"),
                            ("report", "学习报告"),
                            ("grammar_guide", "语法导学"),
                            ("rag", "RAG检索"),
                            ("agents", "多Agent简报"),
                        ],
                        default="study_coach",
                        max_length=32,
                        verbose_name="功能类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="标题"
                    ),
                ),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="上下文"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "进行中"), ("archived", "已归档")],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI会话",
                "verbose_name_plural": "AI会话",
                "db_table": "ai_conversations",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "系统"),
                            ("user", "用户"),
                            ("assistant", "AI"),
                        ],
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="内容"),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="结构化内容"
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="提示词版本"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="模型"
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时毫秒"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.aiconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI消息",
                "verbose_name_plural": "AI消息",
                "db_table": "ai_messages",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AIStudyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "周报"), ("monthly", "月报")],
                        default="weekly",
                        max_length=16,
                        verbose_name="报告类型",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="开始日期")),
                ("period_end", models.DateField(verbose_name="结束日期")),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="标题"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="报告内容"),
                ),
                (
                    "source_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="数据快照"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_study_reports",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI学习报告",
                "verbose_name_plural": "AI学习报告",
                "db_table": "ai_study_reports",
                "ordering": ["-period_end", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AIUserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="功能类型"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("helpful", "有帮助"),
                            ("neutral", "一般"),
                            ("unhelpful", "没帮助"),
                            ("wrong", "内容有误"),
                        ],
                        default="helpful",
                        max_length=16,
                        verbose_name="评价",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="反馈内容"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_items",
                        to="ai.aiconversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_items",
                        to="ai.aimessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback_items",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI反馈",
                "verbose_name_plural": "AI反馈",
                "db_table": "ai_user_feedback",
                "ordering": ["-id"],
            },
        ),
    ]
