# Generated by Django 5.2.5 on 2026-04-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("users", "0007_usersetting_speech_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIResponseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="功能类型"
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(max_length=64, unique=True, verbose_name="缓存键"),
                ),
                (
                    "request_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="请求哈希"
                    ),
                ),
                (
                    "response_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="响应载荷"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="过期时间"),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(default=0, verbose_name="命中次数"),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近命中时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI响应缓存",
                "verbose_name_plural": "AI响应缓存",
                "db_table": "ai_response_cache",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AlterField(
            model_name="aiconversation",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("grammar", "语法问答"),
                    ("word", "AI讲词"),
                    ("study_coach", "学习教练"),
                    ("wrong_words", "错词复盘"),
                    ("writing", "写作批改"),
                    ("translation", "翻译训练"),
                    ("report", "学习报告"),
                    ("grammar_guide", "语法导学"),
                    ("rag", "RAG检索"),
                    ("vector_rag", "向量RAG"),
                    ("agents", "多Agent简报"),
                    ("writing_prompt", "写作题目范文"),
                    ("scenario", "情景文本对话"),
                    ("observability", "AI观测"),
                ],
                default="study_coach",
                max_length=32,
                verbose_name="功能类型",
            ),
        ),
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="功能类型"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="接口"
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="缓存键",
                    ),
                ),
                (
                    "cache_hit",
                    models.BooleanField(default=False, verbose_name="是否命中缓存"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("rate_limited", "限流"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时毫秒"),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="提示词版本"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="模型"
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="请求载荷"),
                ),
                (
                    "response_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="响应载荷"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_request_logs",
                        to="users.wxuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI运行日志",
                "verbose_name_plural": "AI运行日志",
                "db_table": "ai_run_logs",
                "ordering": ["-id"],
            },
        ),
    ]
