# Generated by Django 5.2.5 on 2026-05-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_airesponsecache_alter_aiconversation_feature_type_and_more"),
        ("users", "0007_usersetting_speech_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEvaluationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Case Name")),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("rag_recall", "RAG Recall"),
                            ("plan_replan", "Plan Replan"),
                            ("study_coach", "Study Coach"),
                            ("conversation", "Conversation"),
                        ],
                        default="rag_recall",
                        max_length=32,
                        verbose_name="Case Type",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "input_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Input Payload"
                    ),
                ),
                (
                    "expected_signals",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Expected Signals"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Evaluation Case",
                "verbose_name_plural": "AI Evaluation Case",
                "db_table": "ai_evaluation_cases",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AIEvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Feature Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        default="passed",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Score"
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Request Payload"
                    ),
                ),
                (
                    "result_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Result Payload"
                    ),
                ),
                (
                    "trace_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Trace Payload"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Failure Reason"
                    ),
                ),
                (
                    "runtime_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Runtime Snapshot"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ai.aievaluationcase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_evaluation_runs",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Evaluation Run",
                "verbose_name_plural": "AI Evaluation Run",
                "db_table": "ai_evaluation_runs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AIUserProfileMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "profile_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="Profile Summary"
                    ),
                ),
                (
                    "weak_points",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Weak Points"
                    ),
                ),
                (
                    "preferred_modes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Preferred Modes"
                    ),
                ),
                (
                    "recent_focus_words",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Recent Focus Words"
                    ),
                ),
                (
                    "profile_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Profile Payload"
                    ),
                ),
                (
                    "memory_version",
                    models.CharField(
                        blank=True,
                        default="memory_v1",
                        max_length=32,
                        verbose_name="Memory Version",
                    ),
                ),
                (
                    "updated_from",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Updated From",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_profile_memory",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI User Profile Memory",
                "verbose_name_plural": "AI User Profile Memory",
                "db_table": "ai_user_profile_memory",
            },
        ),
    ]
