# Generated by Django 5.2.5 on 2026-05-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_aievaluationcase_aievaluationrun_aiuserprofilememory"),
        ("users", "0007_usersetting_speech_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAsyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("feature_type", models.CharField(db_index=True, max_length=32, verbose_name="功能类型")),
                ("public_id", models.CharField(db_index=True, max_length=32, unique=True, verbose_name="运行ID")),
                ("endpoint", models.CharField(blank=True, default="", max_length=128, verbose_name="接口")),
                ("request_hash", models.CharField(db_index=True, max_length=64, verbose_name="请求哈希")),
                ("request_payload", models.JSONField(blank=True, default=dict, verbose_name="请求载荷")),
                ("result_payload", models.JSONField(blank=True, default=dict, verbose_name="结果载荷")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "运行中"),
                            ("succeeded", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("status_text", models.CharField(blank=True, default="", max_length=128, verbose_name="状态说明")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("latency_ms", models.PositiveIntegerField(default=0, verbose_name="耗时毫秒")),
                ("degraded", models.BooleanField(default=False, verbose_name="是否降级")),
                ("retryable", models.BooleanField(default=True, verbose_name="是否可重试")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_async_runs",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 异步任务",
                "verbose_name_plural": "AI 异步任务",
                "db_table": "ai_async_runs",
                "ordering": ["-id"],
            },
        ),
    ]
