# Generated by Django 5.2.5 on 2026-05-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_aiasyncrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aievaluationcase",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("rag_recall", "RAG Recall"),
                    ("vector_rag", "Vector RAG"),
                    ("plan_replan", "Plan Replan"),
                    ("retrieval_orchestrator", "Retrieval Orchestrator"),
                    ("study_coach", "Study Coach"),
                    ("word_tutor", "Word Tutor"),
                    ("wrong_words_review", "Wrong Words Review"),
                    ("grammar_tutor", "Grammar Tutor"),
                    ("conversation", "Conversation"),
                ],
                default="rag_recall",
                max_length=32,
                verbose_name="Case Type",
            ),
        ),
    ]
