# Generated by Django 5.2.5 on 2026-05-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_alter_aievaluationcase_case_type"),
        ("users", "0007_usersetting_speech_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiasyncrun",
            name="approval_state",
            field=models.CharField(
                choices=[
                    ("not_required", "无需审批"),
                    ("pending", "待审批"),
                    ("approved", "已批准"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="not_required",
                max_length=24,
                verbose_name="审批状态",
            ),
        ),
        migrations.AddField(
            model_name="aiasyncrun",
            name="checkpoint_version",
            field=models.CharField(blank=True, default="agent_v1", max_length=32, verbose_name="检查点版本"),
        ),
        migrations.AddField(
            model_name="aiasyncrun",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_runs",
                to="ai.aiconversation",
                verbose_name="关联会话",
            ),
        ),
        migrations.AddField(
            model_name="aiasyncrun",
            name="current_agent",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="当前智能体"),
        ),
        migrations.AddField(
            model_name="aiasyncrun",
            name="parent_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_runs",
                to="ai.aiasyncrun",
                verbose_name="父运行",
            ),
        ),
        migrations.AddField(
            model_name="aiasyncrun",
            name="queue_name",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="队列名称"),
        ),
        migrations.AddField(
            model_name="aiasyncrun",
            name="retry_count",
            field=models.PositiveIntegerField(default=0, verbose_name="重试次数"),
        ),
        migrations.AddField(
            model_name="aiasyncrun",
            name="runtime_kind",
            field=models.CharField(
                choices=[
                    ("legacy_thread", "旧线程运行时"),
                    ("celery", "Celery Worker"),
                    ("inline", "同步运行时"),
                ],
                db_index=True,
                default="legacy_thread",
                max_length=24,
                verbose_name="运行时类型",
            ),
        ),
        migrations.AlterField(
            model_name="aiasyncrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "排队中"),
                    ("running", "运行中"),
                    ("succeeded", "已完成"),
                    ("failed", "失败"),
                    ("waiting_approval", "等待审批"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="AIAgentStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("step_index", models.PositiveIntegerField(db_index=True, default=0, verbose_name="步骤序号")),
                ("step_key", models.CharField(blank=True, default="", max_length=64, verbose_name="步骤键")),
                (
                    "step_kind",
                    models.CharField(
                        choices=[
                            ("agent", "智能体步骤"),
                            ("tool", "工具调用"),
                            ("critic", "校验步骤"),
                            ("system", "系统步骤"),
                        ],
                        default="agent",
                        max_length=16,
                        verbose_name="步骤类型",
                    ),
                ),
                ("agent_name", models.CharField(blank=True, default="", max_length=64, verbose_name="智能体名称")),
                ("title", models.CharField(blank=True, default="", max_length=128, verbose_name="标题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "运行中"),
                            ("succeeded", "已完成"),
                            ("failed", "失败"),
                            ("skipped", "已跳过"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("input_payload", models.JSONField(blank=True, default=dict, verbose_name="输入载荷")),
                ("output_payload", models.JSONField(blank=True, default=dict, verbose_name="输出载荷")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="步骤元数据")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("latency_ms", models.PositiveIntegerField(default=0, verbose_name="耗时毫秒")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "parent_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_steps",
                        to="ai.aiagentstep",
                        verbose_name="父步骤",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="ai.aiasyncrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 智能体步骤",
                "verbose_name_plural": "AI 智能体步骤",
                "db_table": "ai_agent_steps",
                "ordering": ["run_id", "step_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="AIAgentArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("artifact_type", models.CharField(db_index=True, max_length=32, verbose_name="产物类型")),
                ("artifact_key", models.CharField(blank=True, default="", max_length=64, verbose_name="产物键")),
                ("title", models.CharField(blank=True, default="", max_length=128, verbose_name="标题")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="产物内容")),
                ("summary", models.TextField(blank=True, default="", verbose_name="摘要")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="ai.aiasyncrun",
                        verbose_name="运行",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="ai.aiagentstep",
                        verbose_name="关联步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 智能体产物",
                "verbose_name_plural": "AI 智能体产物",
                "db_table": "ai_agent_artifacts",
                "ordering": ["run_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="AIAgentApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("approval_key", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="审批键")),
                ("feature_type", models.CharField(db_index=True, max_length=32, verbose_name="功能类型")),
                ("action_type", models.CharField(blank=True, default="", max_length=32, verbose_name="动作类型")),
                ("title", models.CharField(blank=True, default="", max_length=128, verbose_name="标题")),
                ("request_payload", models.JSONField(blank=True, default=dict, verbose_name="审批请求")),
                ("decision_payload", models.JSONField(blank=True, default=dict, verbose_name="审批结果")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("decision_note", models.TextField(blank=True, default="", verbose_name="审批备注")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="审批时间")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ai_agent_actions",
                        to="users.wxuser",
                        verbose_name="审批人",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="ai.aiasyncrun",
                        verbose_name="运行",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to="ai.aiagentstep",
                        verbose_name="关联步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 智能体审批",
                "verbose_name_plural": "AI 智能体审批",
                "db_table": "ai_agent_approvals",
                "ordering": ["-id"],
            },
        ),
    ]
