# Generated by Django 5.2.5 on 2026-04-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("plans", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("learn", "学习"),
                            ("review", "复习"),
                            ("test", "测试"),
                        ],
                        default="learn",
                        max_length=16,
                        verbose_name="来源",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view", "查看"),
                            ("known", "认识"),
                            ("unknown", "不认识"),
                            ("mastered", "已掌握"),
                            ("favorite", "收藏"),
                        ],
                        default="view",
                        max_length=16,
                        verbose_name="动作",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="结果"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, verbose_name="耗时秒数"),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="发生时间")),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_records",
                        to="plans.userplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_records",
                        to="users.wxuser",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_records",
                        to="books.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习记录",
                "verbose_name_plural": "学习记录",
                "db_table": "learning_records",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="备注"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="users.wxuser",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_users",
                        to="books.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏词",
                "verbose_name_plural": "收藏词",
                "db_table": "favorites",
                "ordering": ["-id"],
                "unique_together": {("user", "word")},
            },
        ),
        migrations.CreateModel(
            name="WordProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "mastery_level",
                    models.PositiveSmallIntegerField(default=0, verbose_name="掌握度"),
                ),
                (
                    "learn_count",
                    models.PositiveIntegerField(default=0, verbose_name="学习次数"),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="复习次数"),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(default=0, verbose_name="答对次数"),
                ),
                (
                    "wrong_count",
                    models.PositiveIntegerField(default=0, verbose_name="答错次数"),
                ),
                (
                    "last_learned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近学习时间"
                    ),
                ),
                (
                    "last_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近复习时间"
                    ),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近测试时间"
                    ),
                ),
                (
                    "review_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次复习时间"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="是否收藏"),
                ),
                (
                    "is_mastered",
                    models.BooleanField(default=False, verbose_name="是否掌握"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_progresses",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_progresses",
                        to="users.wxuser",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="books.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词掌握进度",
                "verbose_name_plural": "单词掌握进度",
                "db_table": "word_progress",
                "ordering": ["review_due_at", "-id"],
                "unique_together": {("user", "word")},
            },
        ),
    ]
