# Generated by Django 5.2.5 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningrecord",
            name="extra_payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="correct_streak",
            field=models.PositiveIntegerField(default=0, verbose_name="连续正确次数"),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="ease_factor",
            field=models.FloatField(default=2.3, verbose_name="记忆容易度"),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="interval_days",
            field=models.PositiveIntegerField(default=0, verbose_name="当前间隔天数"),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="last_score",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="最近一次评分"
            ),
        ),
        migrations.AlterField(
            model_name="learningrecord",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("view", "查看"),
                    ("known", "认识"),
                    ("unknown", "不认识"),
                    ("mastered", "已掌握"),
                    ("favorite", "收藏"),
                    ("shadowing", "跟读"),
                    ("speaking", "口语练习"),
                ],
                default="view",
                max_length=16,
                verbose_name="动作",
            ),
        ),
    ]
