# Generated by Django 5.2.5 on 2026-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0002_learningrecord_extra_payload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningrecord",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("view", "查看"),
                    ("known", "认识"),
                    ("unknown", "不认识"),
                    ("mastered", "已掌握"),
                    ("favorite", "收藏"),
                ],
                default="view",
                max_length=16,
                verbose_name="动作",
            ),
        ),
    ]
