# Generated by Django 5.2.5 on 2026-04-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckinRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("checkin_date", models.DateField(verbose_name="打卡日期")),
                (
                    "finished_new_count",
                    models.PositiveIntegerField(default=0, verbose_name="完成新词数"),
                ),
                (
                    "finished_review_count",
                    models.PositiveIntegerField(default=0, verbose_name="完成复习数"),
                ),
                (
                    "total_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="学习分钟数"),
                ),
                (
                    "status",
                    models.CharField(
                        default="success", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "打卡记录",
                "verbose_name_plural": "打卡记录",
                "db_table": "checkin_records",
                "ordering": ["-checkin_date", "-id"],
                "unique_together": {("user", "checkin_date")},
            },
        ),
        migrations.CreateModel(
            name="StudyDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("stat_date", models.DateField(verbose_name="统计日期")),
                (
                    "learned_count",
                    models.PositiveIntegerField(default=0, verbose_name="学习数量"),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="复习数量"),
                ),
                (
                    "test_count",
                    models.PositiveIntegerField(default=0, verbose_name="测试数量"),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(default=0, verbose_name="正确数量"),
                ),
                (
                    "total_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="学习分钟数"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习日统计",
                "verbose_name_plural": "学习日统计",
                "db_table": "study_daily_stats",
                "ordering": ["-stat_date", "-id"],
                "unique_together": {("user", "stat_date")},
            },
        ),
    ]
