# Generated by Django 5.2.5 on 2026-04-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="词书名称")),
                ("category", models.CharField(max_length=64, verbose_name="分类")),
                (
                    "level",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="难度层级"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="简介"),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="单词量"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "cover_color",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="封面颜色"
                    ),
                ),
            ],
            options={
                "verbose_name": "词书",
                "verbose_name_plural": "词书",
                "db_table": "books",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("word", models.CharField(max_length=128, verbose_name="单词")),
                (
                    "phonetic",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="音标"
                    ),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="词性"
                    ),
                ),
                (
                    "meaning_cn",
                    models.CharField(max_length=255, verbose_name="中文释义"),
                ),
                (
                    "example_sentence",
                    models.TextField(blank=True, default="", verbose_name="例句"),
                ),
                (
                    "example_translation",
                    models.TextField(blank=True, default="", verbose_name="例句翻译"),
                ),
                (
                    "audio_url",
                    models.URLField(blank=True, default="", verbose_name="音频地址"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(default=1, verbose_name="难度"),
                ),
                (
                    "synonyms",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="近义词"
                    ),
                ),
                (
                    "order_in_book",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词",
                "verbose_name_plural": "单词",
                "db_table": "words",
                "ordering": ["book_id", "order_in_book", "id"],
            },
        ),
        migrations.CreateModel(
            name="WordExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("example_sentence", models.TextField(verbose_name="例句")),
                (
                    "example_translation",
                    models.TextField(blank=True, default="", verbose_name="例句翻译"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="books.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词例句",
                "verbose_name_plural": "单词例句",
                "db_table": "word_examples",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
