# Generated by Django 5.2.5 on 2026-04-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "title",
                    models.CharField(
                        default="词汇小测", max_length=128, verbose_name="测试标题"
                    ),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(default=0, verbose_name="题目数"),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(default=0, verbose_name="答对数"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="得分"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "未完成"), ("completed", "已完成")],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_sessions",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to="users.wxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试会话",
                "verbose_name_plural": "测试会话",
                "db_table": "test_sessions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question_type",
                    models.CharField(
                        default="word_to_meaning", max_length=32, verbose_name="题型"
                    ),
                ),
                ("stem", models.CharField(max_length=255, verbose_name="题干")),
                ("option_a", models.CharField(max_length=255, verbose_name="选项A")),
                ("option_b", models.CharField(max_length=255, verbose_name="选项B")),
                ("option_c", models.CharField(max_length=255, verbose_name="选项C")),
                ("option_d", models.CharField(max_length=255, verbose_name="选项D")),
                (
                    "correct_option",
                    models.CharField(max_length=1, verbose_name="正确选项"),
                ),
                (
                    "explanation",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="解析"
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_questions",
                        to="books.word",
                    ),
                ),
                (
                    "test_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.testsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试题目",
                "verbose_name_plural": "测试题目",
                "db_table": "test_questions",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True, default="", max_length=1, verbose_name="选择项"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确"),
                ),
                ("answered_at", models.DateTimeField(verbose_name="答题时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_answers",
                        to="users.wxuser",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.testquestion",
                    ),
                ),
                (
                    "test_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.testsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试答案",
                "verbose_name_plural": "测试答案",
                "db_table": "test_answers",
                "ordering": ["-answered_at", "-id"],
                "unique_together": {("test_session", "question")},
            },
        ),
    ]
