# Generated by Django 5.2.5 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testanswer",
            name="submitted_text",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="文本作答"
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="answer_mode",
            field=models.CharField(
                default="choice", max_length=16, verbose_name="作答方式"
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="answer_text",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="文本答案"
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="cefr_tag",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="CEFR标签"
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="difficulty_level",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="难度等级"),
        ),
        migrations.AddField(
            model_name="testsession",
            name="cefr_result",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="CEFR结果"
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="extra_payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AddField(
            model_name="testsession",
            name="session_type",
            field=models.CharField(
                default="practice", max_length=32, verbose_name="测试类型"
            ),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="correct_option",
            field=models.CharField(
                blank=True, default="", max_length=1, verbose_name="正确选项"
            ),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="option_a",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="选项A"
            ),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="option_b",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="选项B"
            ),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="option_c",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="选项C"
            ),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="option_d",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="选项D"
            ),
        ),
    ]
