# Generated by Django 5.2.5 on 2026-04-23 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="编码"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="语法点名称")),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="分类"
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(default=1, verbose_name="难度"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="说明"),
                ),
                (
                    "learning_tip",
                    models.TextField(blank=True, default="", verbose_name="学习提示"),
                ),
                (
                    "practice_prompt",
                    models.TextField(
                        blank=True, default="", verbose_name="默认练习题干"
                    ),
                ),
                (
                    "practice_options",
                    models.JSONField(
                        blank=True, default=list, verbose_name="默认练习选项"
                    ),
                ),
                (
                    "practice_answer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="默认练习答案",
                    ),
                ),
                (
                    "practice_explanation",
                    models.TextField(
                        blank=True, default="", verbose_name="默认练习解析"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=16, verbose_name="状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "语法点",
                "verbose_name_plural": "语法点",
                "db_table": "grammar_points",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GrammarSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("sentence", models.CharField(max_length=512, verbose_name="英文句子")),
                ("translation_cn", models.TextField(verbose_name="中文翻译")),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="核心说明"
                    ),
                ),
                (
                    "analysis",
                    models.TextField(blank=True, default="", verbose_name="句子解析"),
                ),
                (
                    "main_structure",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="主干结构"
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(default=1, verbose_name="难度"),
                ),
                (
                    "scene_tag",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="场景标签"
                    ),
                ),
                (
                    "grammar_tags",
                    models.JSONField(blank=True, default=list, verbose_name="语法标签"),
                ),
                (
                    "chunk_breakdown",
                    models.JSONField(blank=True, default=list, verbose_name="分块拆解"),
                ),
                (
                    "audio_url",
                    models.URLField(blank=True, default="", verbose_name="音频地址"),
                ),
                (
                    "is_long_sentence",
                    models.BooleanField(default=False, verbose_name="是否长难句"),
                ),
                (
                    "practice_type",
                    models.CharField(
                        default="choice", max_length=32, verbose_name="练习类型"
                    ),
                ),
                (
                    "practice_prompt",
                    models.TextField(blank=True, default="", verbose_name="练习题干"),
                ),
                (
                    "practice_options",
                    models.JSONField(blank=True, default=list, verbose_name="练习选项"),
                ),
                (
                    "practice_answer",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="练习答案"
                    ),
                ),
                (
                    "practice_explanation",
                    models.TextField(blank=True, default="", verbose_name="练习解析"),
                ),
                (
                    "order_in_point",
                    models.PositiveIntegerField(default=0, verbose_name="语法点内排序"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="grammar.grammarpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "语法句子",
                "verbose_name_plural": "语法句子",
                "db_table": "grammar_sentences",
                "ordering": ["point_id", "order_in_point", "id"],
            },
        ),
        migrations.CreateModel(
            name="GrammarLearningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view", "查看"),
                            ("understood", "已理解"),
                            ("unclear", "未理解"),
                            ("practice", "完成练习"),
                            ("bookmark", "收藏"),
                        ],
                        default="view",
                        max_length=16,
                        verbose_name="动作类型",
                    ),
                ),
                (
                    "practice_type",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="练习类型"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "无"),
                            ("correct", "正确"),
                            ("wrong", "错误"),
                            ("neutral", "中性"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="结果",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, verbose_name="耗时秒数"),
                ),
                (
                    "mastery_level",
                    models.PositiveSmallIntegerField(default=0, verbose_name="掌握度"),
                ),
                (
                    "extra_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发生时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_learning_records",
                        to="users.wxuser",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_records",
                        to="grammar.grammarpoint",
                    ),
                ),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_records",
                        to="grammar.grammarsentence",
                    ),
                ),
            ],
            options={
                "verbose_name": "语法学习记录",
                "verbose_name_plural": "语法学习记录",
                "db_table": "grammar_learning_records",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GrammarAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "text_span",
                    models.CharField(max_length=255, verbose_name="标注文本"),
                ),
                ("start_index", models.PositiveIntegerField(verbose_name="起始位置")),
                ("end_index", models.PositiveIntegerField(verbose_name="结束位置")),
                ("role_type", models.CharField(max_length=32, verbose_name="语法角色")),
                (
                    "explanation",
                    models.TextField(blank=True, default="", verbose_name="解释"),
                ),
                (
                    "grammar_label",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="标签"
                    ),
                ),
                (
                    "color_token",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="颜色标识"
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(default=False, verbose_name="是否核心成分"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="grammar.grammarannotation",
                        verbose_name="父级标注",
                    ),
                ),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="grammar.grammarsentence",
                    ),
                ),
            ],
            options={
                "verbose_name": "句子标注",
                "verbose_name_plural": "句子标注",
                "db_table": "grammar_annotations",
                "ordering": ["sort_order", "start_index", "id"],
            },
        ),
    ]
